// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type SuusHarsveldDocumentDataSlicesSlice = HeaderBlockSlice | UitgeestSlice;

/**
 * Content for Suus Harsveld documents
 */
interface SuusHarsveldDocumentData {
  /**
   * profile picture field in *Suus Harsveld*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: suus_harsveld.profile_picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * Uitgeest field in *Suus Harsveld*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: suus_harsveld.uitgeest
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  uitgeest: prismic.GeoPointField;

  /**
   * Slice Zone field in *Suus Harsveld*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: suus_harsveld.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SuusHarsveldDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Suus Harsveld*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: suus_harsveld.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Suus Harsveld*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: suus_harsveld.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Suus Harsveld*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: suus_harsveld.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Suus Harsveld document from Prismic
 *
 * - **API ID**: `suus_harsveld`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SuusHarsveldDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SuusHarsveldDocumentData>,
    "suus_harsveld",
    Lang
  >;

/**
 * Content for Uitgeest documents
 */
interface UitgeestDocumentData {
  /**
   * Uitgeest field in *Uitgeest*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: uitgeest.uitgeest
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  uitgeest: prismic.GeoPointField;
}

/**
 * Uitgeest document from Prismic
 *
 * - **API ID**: `uitgeest`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UitgeestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UitgeestDocumentData>,
    "uitgeest",
    Lang
  >;

export type AllDocumentTypes = SuusHarsveldDocument | UitgeestDocument;

/**
 * Primary content in *HeaderBlock → Primary*
 */
export interface HeaderBlockSliceDefaultPrimary {
  /**
   * slimy field in *HeaderBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_block.primary.slimy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slimy: prismic.RichTextField;
}

/**
 * Default variation for HeaderBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderBlock*
 */
type HeaderBlockSliceVariation = HeaderBlockSliceDefault;

/**
 * HeaderBlock Shared Slice
 *
 * - **API ID**: `header_block`
 * - **Description**: HeaderBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderBlockSlice = prismic.SharedSlice<
  "header_block",
  HeaderBlockSliceVariation
>;

/**
 * Default variation for Uitgeest Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UitgeestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Uitgeest*
 */
type UitgeestSliceVariation = UitgeestSliceDefault;

/**
 * Uitgeest Shared Slice
 *
 * - **API ID**: `uitgeest`
 * - **Description**: Uitgeest
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UitgeestSlice = prismic.SharedSlice<
  "uitgeest",
  UitgeestSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SuusHarsveldDocument,
      SuusHarsveldDocumentData,
      SuusHarsveldDocumentDataSlicesSlice,
      UitgeestDocument,
      UitgeestDocumentData,
      AllDocumentTypes,
      HeaderBlockSlice,
      HeaderBlockSliceDefaultPrimary,
      HeaderBlockSliceVariation,
      HeaderBlockSliceDefault,
      UitgeestSlice,
      UitgeestSliceVariation,
      UitgeestSliceDefault,
    };
  }
}
