// Code generated by Slice Machine. DO NOT EDIT.

import HeaderBlock from "./HeaderBlock/index.svelte";
import Uitgeest from "./Uitgeest/index.svelte";

export const components = {
  header_block: HeaderBlock,
  uitgeest: Uitgeest,
};
