// Code generated by Slice Machine. DO NOT EDIT.

import Button from "./Button/index.svelte";
import Naam from "./Naam/index.svelte";
import ProfilePicture from "./ProfilePicture/index.svelte";

export const components = {
  button: Button,
  naam: Naam,
  profile_picture: ProfilePicture,
};
